
server:
  port: 8081
  servlet:
    context-path: /dev-api


#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dx-server?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root





logging:
  file:
    path: /home/logs


#rocketmq:
#  name-server: 10.1.46.64:9876
#  producer:
#    group: test-group
#